### ISSUE TITLE
C stack usage error

### ISSUE THREAD

**Issue by waynelapierre** [HenrikBengtsson/future.apply#86] opened 2021-06-17 19:07 UTC
I need to apply a simple function to a small vector. lapply works but future_lapply returns an error message: 
`Error: C stack usage  7969908 is too close to the limit`

Could you please offer me a hint about why this happened? Thanks.

**Comment by HenrikBengtsson** [comment] 2021-06-17 20:35
This type of error has started to show up here and there recently - also outside of the future framework, e.g. they're investigating a similar thing over at Bioconductor.  I've also seen it at times, with and without futures.  I haven't had time to investigate.  Hopefully, it's something in base R, and hopefully it'll be investigated and troubleshooted there (sparing me the time).

If you can come up with a minimal reproducible example + `sessionInfo()`, that might help narrow it down.

**Comment by waynelapierre** [comment] 2021-06-17 21:14
Thanks for the reply. My code is as below:

```
require(data.table)
require(rvest)
require(future.apply)
setDTthreads(0)
plan(multicore)
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

url_array <- paste0("https://www.cdc.gov/drugoverdose/maps/rxcounty", 2006:2019, ".html")

file_array <- paste0("url", 2006:2019)

download.file(url_array, file_array)

extract_table <- function(x)
{
  year <- as.integer(substr(x, 4, 7))
  res <- read_html(x)
  
  
  res <- html_table(res)
  
  res <- res[[1]]
  
  setDT(res)
  
  if (year %in% c(2017, 2019))
  {
    setnames(res, c("state", "county", "fips", "OpioidPrescription"))
  }
  else
  {
    setnames(res, c("county", "state", "fips", "OpioidPrescription"))
  }
  
  res[, OpioidPrescription := as.character(OpioidPrescription)]
  res[, OpioidPrescription := fifelse(OpioidPrescription == "–", as.character(NA), OpioidPrescription)]
  res[, OpioidPrescription := as.numeric(OpioidPrescription)]
  res[, year := year]
  
  setcolorder(res, c("fips", "year", "state", "county", "OpioidPrescription"))
  
  return(res)
}

lapply(file_array, extract_table) #working 
future_lapply(file_array, extract_table) #error 

```
session information:

```
R version 4.0.5 (2021-03-31)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 34 (Workstation Edition)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libflexiblas.so.3.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.5 tools_4.0.5   

```

**Comment by waynelapierre** [comment] 2021-07-03 03:39
The example code on the future.apply manual also generates this error. 

```
plan(multisession)
y1 <- future_lapply(1:5, FUN = rnorm, future.seed = 0xBEEF)
Error: C stack usage  7972036 is too close to the limit

```

**Comment by HenrikBengtsson** [comment] 2021-07-08 06:29
Thanks, but I can't reproduce this one;

```r
> library(future.apply)
Loading required package: future
> plan(multisession, workers = 8)
> y1 <- future_lapply(1:5, FUN = rnorm, future.seed = 0xBEEF)
> 
```

```r
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /software/c4/cbi/software/R-4.0.5/lib64/R/lib/libRblas.so
LAPACK: /software/c4/cbi/software/R-4.0.5/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8    LC_NUMERIC=C            LC_TIME=C              
 [4] LC_COLLATE=en_US.UTF-8  LC_MONETARY=C           LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=C              LC_NAME=C               LC_ADDRESS=C           
[10] LC_TELEPHONE=C          LC_MEASUREMENT=C        LC_IDENTIFICATION=C    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] future.apply_1.7.0 future_1.21.0     

loaded via a namespace (and not attached):
[1] compiler_4.0.5    parallelly_1.26.1 startup_0.15.0    parallel_4.0.5   
[5] tools_4.0.5       listenv_0.8.0     codetools_0.2-18  digest_0.6.27    
[9] globals_0.14.0   
```

**Comment by waynelapierre** [comment] 2021-07-08 07:01
for some unknown reason, this issue is gone. this really puzzles me.

**Comment by HenrikBengtsson** [comment] 2021-09-27 05:17
Closing. Filing this one under random hiccups.

**Closed** 2021-09-27 05:17 UTC
