### ISSUE TITLE
Binary does not install on Windows 7 because installation of dependency "globals" fails

### ISSUE THREAD

**Issue by ecoquant** [HenrikBengtsson/future.apply#14] opened 2018-06-25 13:22 UTC
`
R version 3.5.0 Patched (2018-05-03 r74693) -- "Joy in Playing"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Welcome at Mon Jun 25 09:19:35 2018 
> chooseCRANmirror()
> install.packages(c("future.apply"))
also installing the dependency ‘globals’

  There is a binary version available but the source version is later:
        binary source needs_compilation
globals 0.12.0 0.12.1             FALSE

trying URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.5/future.apply_1.0.0.zip'
Content type 'application/zip' length 109235 bytes (106 KB)
downloaded 106 KB

package ‘future.apply’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\Jan\AppData\Local\Temp\RtmpCySh7m\downloaded_packages
installing the source package ‘globals’

trying URL 'https://cran.cnr.berkeley.edu/src/contrib/globals_0.12.1.tar.gz'
Content type 'application/x-gzip' length 20775 bytes (20 KB)
downloaded 20 KB

Welcome at Mon Jun 25 09:20:04 2018 
* installing *source* package 'globals' ...
** package 'globals' successfully unpacked and MD5 sums checked
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'globals'
    finding HTML links ... done
    Globals                                 html  
    cleanup.Globals                         html  
    globalsByName                           html  
    globalsOf                               html  
    packagesOf.Globals                      html  
    walkAST                                 html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64

Welcome at Mon Jun 25 09:20:21 2018 

Goodbye at  Mon Jun 25 09:20:22 2018 
ERROR: loading failed for 'i386'
* removing 'C:/Program Files/R/R-2.13.1/library/globals'
* restoring previous 'C:/Program Files/R/R-2.13.1/library/globals'
In R CMD INSTALL
Warning in install.packages(c("future.apply")) :
  installation of package ‘globals’ had non-zero exit status

The downloaded source packages are in
        ‘C:\Users\Jan\AppData\Local\Temp\RtmpCySh7m\downloaded_packages’
> 
`

**Comment by HenrikBengtsson** [comment] 2018-06-25 14:40
Thanks for reporting.  Hmm... A new version of [globals 0.12.1](https://cran.r-project.org/web/packages/globals/) is rolling out on CRAN right now and the Windows binaries are still at 0.12.0.  However, this should _not_ matter and the globals package should still install just fine.  There's also no native code in the globals package, meaning 0.12.1 should install equally well from source as from a pre-built binary.

All I can imagine is that there was some hiccup out there.  What happens if you try to install only the globals package:
```r
install.packages("globals")
```
?

Also, I cannot reproduce this on my test-Windows 8.1 (VM) with R 3.5.0 using the same CRAN mirror as you and a fresh package library;
```r
> .libPaths(tempdir())
> install.packages("future.apply")
Installing package into 'C:/Users/hb/AppData/Local/Temp/RtmpyQiyus/a'
(as 'lib' is unspecified)
also installing the dependencies 'digest', 'listenv', 'future', 'globals'


  There is a binary version available but the source version is later:
        binary source needs_compilation
globals 0.12.0 0.12.1             FALSE

trying URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.5/digest_0.6.15.zip'
Content type 'application/zip' length 192892 bytes (188 KB)
downloaded 188 KB

trying URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.5/listenv_0.7.0.zip'
Content type 'application/zip' length 101691 bytes (99 KB)
downloaded 99 KB

trying URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.5/future_1.8.1.zip'
Content type 'application/zip' length 527363 bytes (515 KB)
downloaded 515 KB

trying URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.5/future.apply_1.0.0.zip'
Content type 'application/zip' length 109235 bytes (106 KB)
downloaded 106 KB

package 'digest' successfully unpacked and MD5 sums checked
package 'listenv' successfully unpacked and MD5 sums checked
package 'future' successfully unpacked and MD5 sums checked
package 'future.apply' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\hb\AppData\Local\Temp\RtmpyQiyus\downloaded_packages
installing the source package 'globals'

trying URL 'https://cran.cnr.berkeley.edu/src/contrib/globals_0.12.1.tar.gz'
Content type 'application/x-gzip' length 20775 bytes (20 KB)
downloaded 20 KB

* installing *source* package 'globals' ...
** package 'globals' successfully unpacked and MD5 sums checked
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'globals'
    finding HTML links ... done
    Globals                                 html  
    cleanup.Globals                         html  
    globalsByName                           html  
    globalsOf                               html  
    packagesOf.Globals                      html  
    walkAST                                 html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (globals)
In R CMD INSTALL

The downloaded source packages are in
        'C:\Users\hb\AppData\Local\Temp\RtmpyQiyus\downloaded_packages'
```

I'm using continuous-integration testing also on Windows, and this issue is not detected there either, e.g https://ci.appveyor.com/project/HenrikBengtsson/future-apply/history.

**Comment by HenrikBengtsson** [comment] 2018-06-25 14:45
Oh, wait a minute, your startup message says you're using R 3.5.0 patched:
```r
R version 3.5.0 Patched (2018-05-03 r74693) -- "Joy in Playing"
[...]
```
but the library path in the installation error message suggests that you're using R 2.13.1:
```r
ERROR: loading failed for 'i386'

removing 'C:/Program Files/R/R-2.13.1/library/globals'
restoring previous 'C:/Program Files/R/R-2.13.1/library/globals'
In R CMD INSTALL
Warning in install.packages(c("future.apply")) :
installation of package ‘globals’ had non-zero exit status
```

My best guess right now is that you have some `R_LIBS_USER` env var set or some other settings messing with your `.libPaths()`.   Retry by starting a fresh R session, i.e. `R --vanilla`.  That most likely works and gives you something to work with.

**Comment by HenrikBengtsson** [comment] 2018-06-26 23:03
FYI, the Windows binary for globals 0.12.1 is now available on CRAN.  Please let me know if I can close this issue.

**Comment by HenrikBengtsson** [comment] 2018-07-04 19:20
I'll assume you've resolved this. Please reopen if you still think there's something that should be resolved in the future ecosystem.

**Closed** 2018-07-04 19:20 UTC
