### ISSUE TITLE
Error: external pointer error

### ISSUE THREAD

**Issue by krose** [HenrikBengtsson/future.apply#4] opened 2018-01-28 17:56 UTC
I suspect this has something to do with the xml2 package, but I'm not getting the error when using the standard lapply function. Do you have any suggestions how to avoid this error?

Here's my session info:

```

Session info ------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, mingw32             
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  Danish_Denmark.1252         
 tz       Europe/Paris                
 date     2018-01-28                  

Packages ----------------------------------------------------------------------------------------------------------------------------------------------------------
 package      * version date       source                     
 assertthat     0.2.0   2017-04-11 CRAN (R 3.4.2)             
 base         * 3.4.2   2017-09-28 local                      
 bindr          0.1     2016-11-13 CRAN (R 3.4.2)             
 bindrcpp       0.2     2017-06-17 CRAN (R 3.4.2)             
 codetools      0.2-15  2016-10-05 CRAN (R 3.4.2)             
 compiler       3.4.2   2017-09-28 local                      
 curl           3.0     2017-10-06 CRAN (R 3.4.2)             
 datasets     * 3.4.2   2017-09-28 local                      
 devtools     * 1.13.4  2017-11-09 CRAN (R 3.4.2)             
 digest         0.6.12  2017-01-27 CRAN (R 3.4.2)             
 dplyr        * 0.7.4   2017-09-28 CRAN (R 3.4.2)             
 edjao        * 0.1.0   2018-01-28 local                      
 future       * 1.6.2   2017-10-16 CRAN (R 3.4.3)             
 future.apply * 0.1.0   2018-01-15 CRAN (R 3.4.3)             
 globals        0.11.0  2018-01-10 CRAN (R 3.4.3)             
 glue           1.2.0   2017-10-29 CRAN (R 3.4.2)             
 graphics     * 3.4.2   2017-09-28 local                      
 grDevices    * 3.4.2   2017-09-28 local                      
 httr           1.3.1   2017-08-20 CRAN (R 3.4.2)             
 listenv        0.7.0   2018-01-21 CRAN (R 3.4.3)             
 magrittr       1.5     2014-11-22 CRAN (R 3.4.2)             
 memoise        1.1.0   2017-04-21 CRAN (R 3.4.2)             
 methods      * 3.4.2   2017-09-28 local                      
 parallel       3.4.2   2017-09-28 local                      
 pkgconfig      2.0.1   2017-03-21 CRAN (R 3.4.2)             
 R6             2.2.2   2017-06-17 CRAN (R 3.4.2)             
 Rcpp           0.12.15 2018-01-20 CRAN (R 3.4.3)             
 rlang          0.1.4   2017-11-05 CRAN (R 3.4.2)             
 stats        * 3.4.2   2017-09-28 local                      
 tibble         1.3.4   2017-08-22 CRAN (R 3.4.2)             
 tools          3.4.2   2017-09-28 local                      
 utils        * 3.4.2   2017-09-28 local                      
 withr          2.1.0   2017-11-01 CRAN (R 3.4.2)             
 xml2         * 1.2.0   2018-01-28 Github (r-lib/xml2@81ab26b)
 yaml           2.1.14  2016-11-12 CRAN (R 3.4.2)    

```

Here's some code to reproduce the error

```

library(xml2)
library(dplyr)
library(future.apply)

# function to parse individual children
get_xml_content <- function(x){
  
  x_xml <- xml_children(x)
  parsed_xml <- matrix(xml2::xml_text(x_xml), nrow = 1)
  colnames(parsed_xml) <- xml2::xml_name(x_xml)
  
  parsed_xml
}

###### Create and read some data

# Create xml
x_content <- paste(rep("<a><contentA>A</contentA><contentB>B</contentB><contentC>C</contentC></a>", times = 10000), collapse = "")
x <- read_xml(paste0("<body>", x_content, "</body>"))

# get children
x <- xml2::xml_children(x)


###### parse children

# works
lapply(x, get_xml_content)

# doesn't work (few of the things I have tried)
future_lapply(x, get_xml_content)
future_lapply(x, get_xml_content, future.globals = list(x = x, get_xml_content = get_xml_content))
future_lapply(x, get_xml_content, future.globals = FALSE, future.packages = c("base", "xml2"))
future_lapply(x, get_xml_content, future.lazy = TRUE)

plan(multisession)
future_lapply(x, get_xml_content)

```

**Comment by HenrikBengtsson** [comment] 2018-01-28 20:05
Yeah, there is a set of object types that cannot be passed on to another R process and be expected to work there.  Some of the `xml2` objects seem to belong to this set.  Other examples are [connections](https://github.com/HenrikBengtsson/future/issues/79), and [locally `R.cpp::sourceCpp()` compiled C++ code](https://stackoverflow.com/questions/25606733/using-rcpp-function-in-parlapply-on-windows/25606950). This is not a limitation of the future framework or any other parallelizing framework per se, but to those objects and their implementations.  I'm thinking looking for such objects in the future framework and give an early, informative error message about them cannot be used - however it's quite expensive to search for them, so it might be better to leave them to fail as run-time error (as here).

In this case the error produced is:
```r
Error: external pointer is not valid
```
It occurs on the worker side, that is, the worker's R process tries to operate on the xml2 object, but fails because it refers to an "external pointer" that only exists on the master R process.

Here's a minimal reproducible example:
```r
library("xml2")
xml <- read_xml("<body>test</body>")

library("future")
plan(multisession)

f <- future(xml_children(xml))
v <- value(f)
## Error: external pointer is not valid
```

Comment: the error does not occur with `plan(sequential)`, because then the worker process is the same as the master process.  It also does not occur with `plan(multicore)` (Unix-like systems only), because it uses forked processes, which share memory with the master process.

**Comment by HenrikBengtsson** [comment] 2018-01-28 20:09
The only workaround I can imagine for xml2 is to pass a string representation of the XML document and have each worker parse and operate that separately, e.g.
```r
future_lapply(x_strings, FUN = ...)
```
Note that the limitation of external pointers also means that you cannot pass such back to master (i.e. as values).

**Comment by krose** [comment] 2018-01-29 12:22
Thank you for the explanation. It demystified a lot for me.

I converted the xml children to strings, like you suggested, and parse it in the helper function instead. It improved the execution speed by ~40%. Thanks for the 'pointer'!

**Comment by HenrikBengtsson** [comment] 2018-02-01 05:15
In the future package, I've now got [a prototype working that automatically protects against non-exportable globals](https://github.com/HenrikBengtsson/future/issues/191#issuecomment-362158275.) (e.g. those that contain external pointers as reported here).  In this case, instead of:
```r
> plan(multisession, workers = 2L)
> y <- future_lapply(x, get_xml_content)
Error: external pointer is not valid
```
it would now produce:
```r
> options(future.globals.onReference = "error")
> y <- future_lapply(x, get_xml_content)
Error: Detected a non-exportable reference ('externalptr') in one of the globals used in the future expression
```
_prior_ to trying to actually sending anything the background workers.

**Comment by HenrikBengtsson** [comment] 2018-02-04 20:19
These type of issues will now be documented in the future package vignettes: https://github.com/HenrikBengtsson/future/blob/develop/vignettes/future-2-issues.md.rsp.  It also mentions the prototype mechanism (option `future.globals.onReference`) for detecting these cases.

Closing this one ...

**Closed by HenrikBengtsson** 2018-02-04 20:19 UTC
