### ISSUE TITLE
Not exporting variable that is assigned again in apply function

### ISSUE THREAD

**Issue by renkun-ken** [HenrikBengtsson/future.apply#47] opened 2019-10-30 09:52 UTC
Consider the following cases:

```r
library(future)
plan(multisession, workers = 3)

a <- 1
b <- 2

# case 1
res <- future.apply::future_lapply(1:3, function(i) {
  if (TRUE) {
    a <- a + 1
  }
  a
})

# case 2
res <- future.apply::future_lapply(1:3, function(i) {
  if (FALSE) {
    a <- a + 1
  }
  a
})

# case3
res <- future.apply::future_lapply(1:3, function(i) {
  if (a < b) {
    a <- a + 1
  }
  a
})

# case4
res <- future.apply::future_lapply(1:3, function(i) {
  if (a > b) {
    a <- a + 1
  }
  a
})
```

Case2-4 will end up in the following error:

```
Error in ...future.FUN(...future.X_jj, ...) : object 'a' not found
```

It seems that if a global variable that is assigned again in a `FALSE` or non-determined condition, the global variable will not be exported to the worker.

But the behavior is inconsistent with how `future` determines which global variables to export to workers.

```r
task1 <- future({
  if (TRUE) {
    a <- a + 1
  }
  a
})

task2 <- future({
  if (FALSE) {
    a <- a + 1
  }
  a
})

task3 <- future({
  if (a < b) {
    a <- a + 1
  }
  a
})

task4 <- future({
  if (a > b) {
    a <- a + 1
  }
  a
})

res <- values(list(task1, task2, task3, task4))
```

which produces the correct results without such error.

**Comment by renkun-ken** [comment] 2019-10-31 03:34
Thanks for pointing to the vignettes. I'll avoid such usage at the moment.

**Comment by HenrikBengtsson** [comment] 2019-11-02 03:37
UPDATE: This has been fixed in the [develop version of the globals package](https://github.com/HenrikBengtsson/globals/tree/develop).

**Comment by HenrikBengtsson** [comment] 2019-11-02 03:53
I've now also added package tests for future.apply that will test for this when globals (> 0.12.4) is released.  I'm closing since there's nothing else to do in the future.apply package.

**Closed by HenrikBengtsson** 2019-11-02 03:53 UTC
Labels: bug

**Comment by renkun-ken** [comment] 2019-11-02 04:19
Thanks! I'll test it soon.

**Comment by geryan** [comment] 2019-11-27 05:47
A note for future reference that I've been getting the same error
`Error in ...future.FUN(...future.X_jj, ...) : object 'result' not found`
occurring under a `future_lapply` call to a function that internally creates (assigns) and then returns an object called `result`.

**The problem can be fixed by changing the object name inside the function to something other than** `result`**.**

I can't create a simple reproducible example, but I'm guessing the problem might be occurring because of a conflict with future's use of `result`.

**Comment by HenrikBengtsson** [comment] 2019-11-27 05:51
Thxs @geryan. Reproducible examples are always useful, so please share.  BTW, does
```r
remotes::install_github("HenrikBengtsson/globals@develop")
```
fix your problem?
